name: Build and Publish Docker
on:
  push:
    branches:
      - master
jobs:
  canary:
    runs-on: ubuntu-latest
    name: build docker
    steps:
      - uses: actions/checkout@master
      - name: Publish to Docker Repository
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ispeakcode/docker-githubaction
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}